DELIMITER $
create trigger INSERT_SPJ 
AFTER INSERT on SPJ
for each row
begin
  IF EXISTS(select * from SPJ_SUMQTY WHERE JNO=NEW.JNO AND PNO=NEW.PNO)
  THEN UPDATE SPJ_SUMQTY SET SUMQTY = SUMQTY+NEW.QTY WHERE JNO=NEW.JNO AND PNO=NEW.PNO;
  ELSE INSERT INTO SPJ_SUMQTY(JNO,PNO,SUMQTY)
  VALUES(NEW.JNO,NEW.PNO,NEW.QTY);
  END IF;
end $
DELIMITER ;

